[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$EMJ4772X8h5DyBljzPn//w$/2Iuw94XpWxSYansCuTZ3MpFKb2vUNP6NX00PIVZRbFWZcOkOC.2lRzP3FDVUzGSl8Fh.SBRTfV2odOE.HDVCw
log_level = info

